"""auto_20260505_002715

Revision ID: 1d706e588809
Revises: c3f1a2d4e5b6
Create Date: 2026-05-05 00:27:37.352659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '1d706e588809'
down_revision: Union[str, None] = 'c3f1a2d4e5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_job_user_created', table_name='job')
    op.add_column('thumbnail', sa.Column('imagekit_file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('idx_thumbnail_job_id', table_name='thumbnail')
    op.drop_index('idx_thumbnail_user_created', table_name='thumbnail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_thumbnail_user_created', 'thumbnail', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_thumbnail_job_id', 'thumbnail', ['job_id'], unique=False)
    op.drop_column('thumbnail', 'imagekit_file_id')
    op.create_index('idx_job_user_created', 'job', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
